[build]
  base = "cvnova-website"
  publish = "out"
  command = "npm ci && npm run build"
  functions = "netlify/functions" 

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Handle API routes with Netlify Functions (must come before catch-all)
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true

# Handle client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
